=== GabrielaGP2023/ejercicios_xml_2/ejercicio_1_xsd.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="biblioteca">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="libro" maxOccurs="unbounded" minOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="titulo" type="xs:string" />
              <xs:element name="autor" type="xs:string" />
              <xs:element name="editorial" type="xs:string" />
              <xs:element name="aÃ±o" type="xs:int" />
            </xs:sequence>
            <xs:attribute name="idioma" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== GabrielaGP2023/ejercicios_xml_2/ejercicio_1_xsd.xml
<?xml version="1.0"?>
<biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="ejercicio_1_xsd.xsd">
  <libro idioma="es">
    <titulo>El Quijote</titulo>
    <autor>Cervantes</autor>
    <editorial>Alfaguara</editorial>
    <a単o>1605</a単o>
  </libro>
  <libro idioma="es">
    <titulo>El Quijote</titulo>
    <autor>Cervantes</autor>
    <editorial>Alfaguara</editorial>
    <a単o>1605</a単o>
  </libro>
</biblioteca>
