=== GabrielaGP2023/ejercicios_xml_2/ejercicio_1.dtd
<!ELEMENT biblioteca (libro+)>
<!ELEMENT libro (titulo,autor,editorial,año)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT editorial (#PCDATA)>
<!ELEMENT año (#PCDATA)>
<!ATTLIST libro idioma CDATA #IMPLIED>

=== GabrielaGP2023/ejercicios_xml_2/ejercicio_1.xml
<?xml version="1.0"?>
<!DOCTYPE biblioteca SYSTEM "ejercicio_1.dtd">
<biblioteca>
  <libro idioma="es">
    <titulo>El Quijote</titulo>
    <autor>Cervantes</autor>
    <editorial>Alfaguara</editorial>
    <a単o>1605</a単o>
  </libro>
  <libro idioma="es">
    <titulo>El Quijote</titulo>
    <autor>Cervantes</autor>
    <editorial>Alfaguara</editorial>
    <a単o>1605</a単o>
  </libro>
</biblioteca>
