=== GabrielaGP2023/ejercicios_xml_2/repaso_1_xsd.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="alquiler">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="cliente">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string" />
                            <xs:element name="dni" type="xs:string" />
                            <xs:element name="direccion" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="patinete">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="marca" type="xs:string" />
                            <xs:element name="modelo" type="xs:string" />
                            <xs:element name="aÃ±o" type="xs:int" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="fInicio" type="xs:date" />
                <xs:element name="hInicio" type="xs:time" />
                <xs:element name="fFin" type="xs:date" minOccurs="0"/>
                <xs:element name="hFin" type="xs:time" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== GabrielaGP2023/ejercicios_xml_2/repaso_1_xsd.xml
<?xml version="1.0" encoding="UTF-8"?>

<alquiler xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="repaso_1_xsd.xsd">
    <cliente>
        <nombre>Juan López1</nombre>
        <dni>12345678A</dni>
        <direccion>C/ real 12</direccion>
    </cliente>
    <patinete>
        <marca>Mintsubi</marca>
        <modelo>a43</modelo>
        <año>2007</año>
    </patinete>
    <fInicio>2025-05-10</fInicio>
    <hInicio>12:00:00</hInicio>
    <fFin>2025-05-10</fFin>
    <hFin>12:00:00</hFin>


    
</alquiler>
