=== GabrielaGP2023/ejercicios_xml_2/repaso_1_dtd.dtd
<!ELEMENT alquiler (cliente,patinete,fInicio,hInicio,fFin?,hFin?)>
<!ELEMENT cliente (nombre,dni,direccion)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT dni (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT patinete (marca,modelo,año)>
<!ELEMENT marca (#PCDATA)>
<!ELEMENT modelo (#PCDATA)>
<!ELEMENT año (#PCDATA)>
<!ELEMENT fInicio (#PCDATA)>
<!ELEMENT hInicio (#PCDATA)>
<!ELEMENT fFin (#PCDATA)>
<!ELEMENT hFin (#PCDATA)>

=== GabrielaGP2023/ejercicios_xml_2/repaso_1_dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE alquiler SYSTEM "repaso_1_dtd.dtd">
<alquiler>
    
    <cliente>
        <nombre>Juan López1</nombre>
        <dni>12345678A</dni>
        <direccion>C/ real 12</direccion>
    </cliente>
    <patinete>
        <marca>Mintsubi</marca>
        <modelo>a43</modelo>
        <año>2007</año>
    </patinete>
    <fInicio>2025-05-10</fInicio>
    <hInicio>12:00:00</hInicio>
    <fFin>2025-05-10</fFin>
    <hFin>12:00:00</hFin>   
</alquiler>
