=== GabrielaGP2023/ejercicios_xml_2/repaso_2_dtd.dtd
<!ELEMENT evento (chef-invitado,restaurante,chef-destacado,asistentes)>
<!ATTLIST evento nombre CDATA #REQUIRED>
<!ELEMENT chef-invitado (nombre,dni,menu-especial)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT dni (#PCDATA)>
<!ELEMENT menu-especial (entrante,plato-1,plato-2,postre)>
<!ELEMENT entrante (#PCDATA)>
<!ELEMENT plato-1 (#PCDATA)>
<!ELEMENT plato-2 (#PCDATA)>
<!ELEMENT postre (#PCDATA)>
<!ELEMENT restaurante (nombre,direccion)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT chef-destacado (nombre,dni)>
<!ELEMENT asistentes (#PCDATA)>

=== GabrielaGP2023/ejercicios_xml_2/repaso_2_dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE evento SYSTEM "repaso_2_dtd.dtd">
<evento nombre="evento 1 del aÃ±o">
    <chef-invitado>
        <nombre>Ana Flores</nombre>
        <dni>123456789A</dni>
        <menu-especial>
            <entrante>xx</entrante>
            <plato-1>xxx</plato-1>
            <plato-2>xxx</plato-2>
            <postre>xxxx</postre>
        </menu-especial>
    </chef-invitado>
    <restaurante>
        <nombre>xxx</nombre>
        <direccion>C/ real 25</direccion>
    </restaurante>
    <chef-destacado>
        <nombre>Ana Flores</nombre>
        <dni>123456789A</dni>
    </chef-destacado>
    <asistentes>30</asistentes>
</evento>
