=== GabrielaGP2023/ejercicios_xml_2/repaso_3_xsd.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="universidad">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="departamentos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="departamento" type="xs:string" />
                            <xs:element name="areas">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="area" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="profesor"
                                                        maxOccurs="unbounded" minOccurs="0">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="nombre"
                                                                    type="xs:string" />
                                                                <xs:element name="num-empleado"
                                                                    type="xs:string" />
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="nombre" use="required" />
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== GabrielaGP2023/ejercicios_xml_2/repaso_3_xsd.xml
<?xml version="1.0" encoding="UTF-8"?>

<universidad xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="repaso_3_xsd.xsd">
    <departamentos>
        <departamento>Ciencias</departamento>
        <areas>
            <area nombre="Matemáticas">
                <profesor>
                    <nombre>Juan López</nombre>
                    <num-empleado>123445</num-empleado>
                </profesor>
                <profesor>
                    <nombre>Juan López</nombre>
                    <num-empleado>123445</num-empleado>
                </profesor>
            </area>
            <area nombre="Matemáticas">
                <profesor>
                    <nombre>Juan López</nombre>
                    <num-empleado>123445</num-empleado>
                </profesor>
            </area>
        </areas>
    </departamentos>
</universidad>
